### ISSUE TITLE
Pipe is not a function?

### ISSUE THREAD

**Issue by dimeks** [Snowflake107/fbdl-core#1]

**Comment by twlite** [comment]
did you await?

**Comment by dimeks** [comment]
no
can you help
look my code]
  app.get("/download3", (req,res) => {
    var URL = req.query.URL;
    fbdl.download(URL)
    .then(res.pipe(fs.createWriteStream(res))
    );
});

**Comment by twlite** [comment]
try 

```js
app.get("/download3", (req,res) => {
    var URL = req.query.URL;
    fbdl.download(URL)
        .then(res => {
            res.pipe(fs.createWriteStream("./file.mp4"));
        });
});
```

**Comment by dimeks** [comment]
i get this error
s !!! At port 3000
(node:5228) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of IncomingMessage

**Comment by twlite** [comment]
@dimeks yeah check that again I forgot to update something 😅

**Comment by dimeks** [comment]
app.get("/download3", (req,res) => {
    var URL = req.query.URL;
    fbdl.download(URL)
        .then(res => {
            res.pipe(fs.createWriteStream("./file.mp4"));
        });
});
i want to pipe throuth browser

**Comment by twlite** [comment]
try 

```js
app.get("/download3", (req,res) => {
    var URL = req.query.URL;
    fbdl.download(URL)
        .then(video => {
            res.attachment("myvideo.mp4");
            video.pipe(res);
        });
});
```

**Comment by dimeks** [comment]
Oh it works perfectly
thx bro
