### ISSUE TITLE
how to save efile gallery directory android

### ISSUE THREAD

**Issue by dimeks** [Snowflake107/fbdl-core#2]
`  app.get("/download3", (req,res) => {
    var URL = req.query.URL;
    fbdl.download(URL)
        .then(video => {
          res.header("Content-Disposition", "attachment;filename=" + encodeURI(URL) + '.mp4');
            video.pipe(res);
        });
});`

**Comment by twlite** [comment]
Try this:

```js
app.get("/download3", async (req, res) => {
    res.header("Content-Disposition", 'attachment; filename="myvideo.mp4"');
    let URL = req.query.URL;
    let stream = await fbdl.download(URL);
    stream.pipe(res);
});
```
